branch-defaults:
  master:
    environment: backend-dev
global:
  application_name: backend
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: Corretto 17 running on 64bit Amazon Linux 2023
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
#업로드할 파일 경로 설정 가능
deploy:
  artifact: build/libs/backend-0.0.1-SNAPSHOT.jar