app:
  jwtSecret: Aslkdjalwidjaslmdnmcnvxleflisdjflskejflidsjflskjefasdsadsadasdqweqewqe123asdsadzxczcadw
  googleClientId: "http://666974459730-6bv37t0c044nns1tnhd8rrosnspbq613.apps.googleusercontent.com"

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/amaDatabase?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 4701

  mail:
    host: smtp.gmail.com
    port: 587
    username: amaspacealert
    password: 49870123!!
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true

  jpa:
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false
      show-sql: true
      properties:
        hibernate.format_sql: true
        dialect: org.hibernate.dialect.MySQL8InnoDBDialect


    logging:
      level:
        org.hibernate.SQL: debug

